name: climbing_route_app
description: A climbing route creator app with AI-powered hold detection

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Image handling
  image_picker: ^1.0.4
  
  # HTTP requests
  tflite_flutter: ^0.12.0
  image: ^4.1.0
  rename_app: ^1.6.0
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.0
  share_plus: ^9.0.0
  uuid: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.2 
  mockito: ^5.4.2
  flutter_native_splash: ^2.4.0 
  flutter_launcher_icons: "^0.14.4"
  

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/CJ.jpg
  
  # Uncomment if you add assets later
  # assets:
  #   - assets/
flutter_native_splash:
  color: "#FF5722"  # deep orange background
  image: assets/CJ.jpg

  android_12:
    image: assets/CJ.jpg
    icon_background_color: "#FF5722"

  ios: true
  android: true
  web: false
